decimalPoint_format: ','
extra_fn_clean_exts: ##from this until end
    - '.duplication_metrics'
    - type: regex
      pattern: '_fastq[12]'
extra_fn_clean_trim:
  - 'Sample_VE-3297_'

custom content:
  order:
    - fastqc
    - mosdepth
    - fastp
    - peddy
    - samtools
    - picard

table_columns_visible:
  FastQC:
    percent_duplicates: False
    percent_gc: False
    avg_sequence_length: False
    percent_fails: False
    total_sequences: False
  fastp:
    pct_adapter: True
    pct_surviving: False
    after_filtering_gc_content: False
    filtering_result_passed_filter_reads: False
    after_filtering_q30_bases: False
    after_filtering_q30_rate: False
    pct_duplication: False
  mosdepth:
    median_coverage: True
    mean_coverage: False
    1_x_pc: False
    5_x_pc: False
    10_x_pc: True
    20_x_pc: False
    30_x_pc: True
    50_x_pc: True
  Peddy:
    family_id: True
    ancestry-prediction: False
    ancestry-prob_het_check: False
    sex_het_ratio: True
    error_sex_check: True
    predicted_sex_sex_check: True
  Picard:
    PCT_PF_READS_ALIGNED: False
    summed_median: False
    summed_mean: True
    PERCENT_DUPLICATION: True
    MEDIAN_COVERAGE: False
    MEAN_COVERAGE: False
    SD_COVERAGE: False
    PCT_30X: False
    PCT_TARGET_BASES_30X: False
    FOLD_ENRICHMENT: False
  Samtools:
    error_rate: False
    non-primary_alignments: False
    reads_mapped: True
    reads_mapped_percent: True
    reads_properly_paired_percent: True
    reads_MQ0_percent: False
    raw_total_sequences: True

# Patriks plug in, addera egna columner till general stats
multiqc_cgs:
  Picard:
    FOLD_80_BASE_PENALTY:
      title: "Fold80"
      description: "Fold80 penalty from picard hs metrics"
      min: 1
      max: 3
      scale: "RdYlGn-rev"
      format: "{:.1f}"
    PCT_SELECTED_BASES:
      title: "Bases on Target"
      description: "On+Near Bait Bases / PF Bases Aligned from Picard HsMetrics"
      format: "{:.2%}"
    STANDARD_DEVIATION:
      title: "Insert size s.d."
      description: "Insert size standard deviation from Picard"
      min: 0
      max: 150
      scale: "RdYlGn-rev"
      format: "{:.1f}"
    ZERO_CVG_TARGETS_PCT:
      title: "Target bases with zero coverage [%]"
      description: "Target bases with zero coverage [%] from Picard"
      min: 0
      max: 100
      scale: "RdYlGn-rev"
      format: "{:.2%}"
  Samtools:
    average_quality:
      title: "Average Quality"
      description: "Ratio between the sum of base qualities and total length from Samtools stats"
      min: 0
      max: 60
      scale: "RdYlGn"
  mosdepth:
     20_x_pc: #Cant get it to work why?
        title: "20x percent"
        description: "Fraction of genome with at least 20X coverage"
        max: 100
        min: 0
        suffix: "%"
        scale: "RdYlGn"

# Galler alla kolumner oberoende pa module!
table_columns_placement:
  mosdepth:
    median_coverage: 504
    # 1_x_pc: 601
    # 5_x_pc: 602
    10_x_pc: 603
    20_x_pc: 604
    30_x_pc: 605
    50_x_pc: 606
  Samtools:
    raw_total_sequences: 500
    reads_mapped: 501
    reads_mapped_percent: 502
    reads_properly_paired_percent: 800
    # error_rate: 700
    # reads_MQ0_percent: 700
    # non-primary_alignments: 700
  Picard:
    PCT_SELECTED_BASES: 902
    FOLD_80_BASE_PENALTY: 701
    # PCT_PF_READS_ALIGNED: 901
    # summed_median: 949
    summed_mean: 950
    STANDARD_DEVIATION: 951
    PERCENT_DUPLICATION: 505
    # MEDIAN_COVERAGE: 1000
    # MEAN_COVERAGE: 1000
    # SD_COVERAGE: 1001
    # PCT_30X: 1002
    # PCT_TARGET_BASES_30X: 1003
    # FOLD_ENRICHMENT: 1000
    ZERO_CVG_TARGETS_PCT: 1100
  #fastp
