default_resources:
  gres: ""
  mem_mb: 0
  mem_per_cpu: 0
  partition: ""
  threads: 0
  time: ""

pbrun_fq2bam:
  gres: "--gres=gpu:"
  mem_mb: 0
  mem_per_cpu: 0
  partition: ""
  threads: 0
  time: ""

pbrun_mutectcaller_t:
  gres: "--gres=gpu:"
  mem_mb: 0
  mem_per_cpu: 0
  partition: ""
  threads: 0
  time: ""
