$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  resources:
    type: string
    description: Path to resources.yaml file
  samples:
    type: string
    description: Path to samples.tsv file
  units:
    type: string
    description: Path to units.tsv file
  trimmer_software:
    type: string
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  reference:
    type: object
    properties:
      fasta:
        type: string
        description: path to reference fasta file
      sites:
        type: string
        description: path to known sites list file
    required:
      - fasta
      - sites
  fastp_pe:
    type: object
    properties:
      benchmark_repeats:
        type: number
        description: set number of times benchmark should be repeated for fastp_pe
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded to fastp
  required:
    - samples
    - units
    - resources
    - default_container
    - reference
