name: Snakemake dry run

on:
  push:
    branches:
     - develop
     - main
  pull_request:
    branches:
     - develop
     - main
  workflow_dispatch:

jobs:
  snakemake-dry-run:
    name: Run snakemake dry run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up Python 3.9
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.9
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: snakemake dry run
        working-directory: .tests/integration
        run: |
          snakemake -n -s ../../workflow/Snakefile
